spring.application.name=oauth_2GITHUB
spring.security.oauth2.client.registration.github.client-id=Ov23libvmZKwF20jp83M
spring.security.oauth2.client.registration.github.client-secret=aebb74224b30296ad8405c1fbcb2edd2da00c6c5